// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: world.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rpc {

  /// <summary>Holder for reflection information generated from world.proto</summary>
  public static partial class WorldReflection {

    #region Descriptor
    /// <summary>File descriptor for world.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static WorldReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgt3b3JsZC5wcm90bxIDcnBjKh4KCFdvcmxkUlBDEhIKDldPUkxEX1JQQ19O",
            "T05FEABiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Rpc.WorldRPC), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum WorldRPC {
    [pbr::OriginalName("WORLD_RPC_NONE")] None = 0,
  }

  #endregion

}

#endregion Designer generated code
